# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Trava JDK 11
      run: wget https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/latest/download/java11-openjdk-dcevm-linux.tar.gz
    - name: Set up Trava JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: "11.0.9"
        architecture: x64
        jdkFile: ./java11-openjdk-dcevm-linux.tar.gz
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
